#!/usr/bin/env python3
"""Validation harness for the NRHP parser (see nrhp/PROTOCOL.md for the metric).

Runs five independent check groups against nrhp/nrhp_inventory.json and writes
nrhp/validation_report.json. GROUND_TRUTH below was hand-verified against the raw
extracted PDF text during recon (each entry was read in full) — it is the parser's
spot-check oracle and must never be generated by the parser itself.
"""

import json
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent

# Hand-verified from the PDF text layer (recon, 2026-07-02). Fields checked exactly.
GROUND_TRUTH = {
    "5":   {"addr": "159 State Street", "name_has": "Chester Wright", "year": 1808, "status": "contributing"},
    "20":  {"addr": "23 Terrace Street", "year": 1860, "status": "contributing",
            "stories": 2.5, "construction": "wood frame", "roof_shape": "gabled"},
    "53":  {"addr": "76 State Street", "demolished": True},
    "71":  {"addr": "44 Main Street", "name_has": "Bruce Block", "year": 1875, "status": "contributing",
            "stories": 3.0, "construction": "brick", "roof_shape": "flat"},
    "72":  {"addr": "32 Main Street", "name_has": "French Block", "year": 1875, "status": "contributing",
            "stories": 3.0, "construction": "brick", "roof_shape": "flat"},
    "184": {"addr": "100 Main Street", "name_has": "Theriault", "year": 1870, "status": "contributing",
            "stories": 3.0, "construction": "wood frame", "roof_shape": "flat"},
    "185": {"addr": "24 Langdon Street", "year": 1900, "status": "contributing",
            "stories": 1.5, "construction": "wood frame", "roof_shape": "gabled"},
    "188": {"addr": "90 Main Street", "addr2": "27 Langdon Street", "name_has": "Langdon Block",
            "year": 1900, "status": "contributing", "stories": 3.0, "construction": "brick", "roof_shape": "flat"},
    "207": {"addr": "54 Elm Street", "year": 1893, "status": "contributing",
            "stories": 3.0, "construction": "brick", "roof_shape": "flat"},
    "208": {"addr": "4 Court Street", "year": 1840, "status": "contributing",
            "stories": 1.5, "construction": "wood frame", "roof_shape": "gabled"},
    "487": {"addr": "112 State Street", "name_has": "Chittenden", "year": 1994,
            "status": "non-contributing", "stories": 5.0},
    "517": {"addr": "70 East State Street", "name_has": "Toby-Goodwin", "year": 1897,
            "status": "contributing", "stories": 2.5},
    "563": {"addr": "159 Main Street", "year": 1940, "status": "non-contributing", "stories": 1.0},
}

# Pipeline building → expected resource number (recon-verified; see PROCESS_NOTES.md)
TARGET_RECOVERY = {
    "100 Main St, Montpelier, VT 05602": "184",
    "112 State St, Montpelier, VT 05602": "487",
    "27 Langdon St, Montpelier, VT 05602": "188",
    "40 Main St, Montpelier, VT 05602": "72",   # inside French Block former range 32-50
    "54 Elm St, Montpelier, VT 05602": "207",
}

COVERAGE_TARGETS = {"status": 0.95, "year_built": 0.90, "stories": 0.80, "construction": 0.75}

# Document's own stated totals (Section 7 intro): 653 resources = 571 contributing
# (560 buildings, 2 sites, 9 structures) + 82 non-contributing (77 buildings, 5 structures).
# Parsed records additionally include demolished/replaced inventory entries the totals exclude.
DOC_TOTALS = {"contributing": 571, "non_contributing": 82}
TOTALS_TOLERANCE = 12


def check_spot(records):
    by_num = {r["resource_number"]: r for r in records}
    failures, checked = [], 0
    for num, gt in GROUND_TRUTH.items():
        rec = by_num.get(num)
        if rec is None:
            failures.append({"num": num, "field": "presence", "expected": "record", "got": None})
            checked += len(gt)
            continue
        for field, want in gt.items():
            checked += 1
            if field == "addr":
                got = rec["addresses"]["current"][0] if rec["addresses"]["current"] else None
            elif field == "addr2":
                got = rec["addresses"]["current"][1] if len(rec["addresses"]["current"]) > 1 else None
            elif field == "name_has":
                got = rec["historic_name"] or ""
                if want.lower() in got.lower():
                    continue
                failures.append({"num": num, "field": field, "expected": want, "got": got})
                continue
            elif field == "year":
                got = rec["year_built"]
            else:
                got = rec.get(field)
            if got != want:
                failures.append({"num": num, "field": field, "expected": want, "got": got})
    return {"checked": checked, "failed": len(failures), "failures": failures,
            "pass": not failures}


def main():
    inv = json.loads((HERE / "nrhp_inventory.json").read_text())
    records, summary = inv["records"], inv["summary"]
    report = {}

    # 1. structural
    report["structural"] = {
        "entries_found": summary["entries_found"],
        "distinct_numbers": summary["distinct_numbers"],
        "expected_numbers": summary["expected"],
        "missing": summary["missing"],
        "duplicates": summary["duplicates"],
        "pass": summary["distinct_numbers"] == summary["expected"]
        and not summary["missing"] and not summary["duplicates"],
    }

    # 2. spot-check fidelity
    report["spot_check"] = check_spot(records)

    # 3. coverage
    n = len(records)
    cov, cov_pass = {}, True
    for field, target in COVERAGE_TARGETS.items():
        rate = sum(1 for r in records if r.get(field) is not None) / n
        cov[field] = {"rate": round(rate, 3), "target": target, "pass": rate >= target}
        cov_pass &= rate >= target
    report["coverage"] = {"fields": cov, "pass": cov_pass}

    # 4. plausibility
    viol = []
    for r in records:
        if r["year_built"] is not None and not (1780 <= r["year_built"] <= 2017):
            viol.append({"num": r["resource_number"], "field": "year_built", "value": r["year_built"]})
        if r["stories"] is not None and not (1 <= r["stories"] <= 6.5):
            viol.append({"num": r["resource_number"], "field": "stories", "value": r["stories"]})
    report["plausibility"] = {"violations": viol, "pass": not viol}

    # 5. target recovery (runs the matcher)
    matches = json.loads((HERE / "nrhp_matches.json").read_text()) if (HERE / "nrhp_matches.json").exists() else {}
    rec_res = {}
    tr_pass = True
    for addr, want in TARGET_RECOVERY.items():
        got = matches.get(addr, {}).get("resource_number")
        ok = got == want
        tr_pass &= ok
        rec_res[addr] = {"expected": want, "got": got, "pass": ok}
    report["target_recovery"] = {"targets": rec_res, "pass": tr_pass,
                                 "note": "run match_buildings.py first" if not matches else None}

    # 6. document-totals reconciliation (informational, tolerance-gated)
    from collections import Counter
    c = Counter(r["status"] for r in records if not r["demolished"])
    diff_c = abs(c.get("contributing", 0) - DOC_TOTALS["contributing"])
    diff_n = abs(c.get("non-contributing", 0) - DOC_TOTALS["non_contributing"])
    report["doc_totals"] = {
        "parsed_contributing": c.get("contributing", 0),
        "parsed_non_contributing": c.get("non-contributing", 0),
        "parsed_status_none": c.get(None, 0),
        "doc_stated": DOC_TOTALS,
        "abs_diff": {"contributing": diff_c, "non_contributing": diff_n},
        "pass": diff_c <= TOTALS_TOLERANCE and diff_n <= TOTALS_TOLERANCE,
    }

    report["ALL_PASS"] = all(report[k]["pass"] for k in
                             ("structural", "spot_check", "coverage", "plausibility",
                              "target_recovery", "doc_totals"))
    (HERE / "validation_report.json").write_text(json.dumps(report, indent=1))
    for k in ("structural", "spot_check", "coverage", "plausibility", "target_recovery", "doc_totals"):
        print(f"{k:16s}: {'PASS' if report[k]['pass'] else 'FAIL'}")
    print("ALL:", "PASS" if report["ALL_PASS"] else "FAIL")
    if report["spot_check"]["failures"]:
        print(json.dumps(report["spot_check"]["failures"], indent=1))
    return 0 if report["ALL_PASS"] else 1


if __name__ == "__main__":
    sys.exit(main())
